// <auto-generated />
using System;
using BlazorApp1.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp1.Migrations
{
    [DbContext(typeof(SupportGestorDbContext))]
    [Migration("20250122184941_raissa")]
    partial class raissa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp1.MVVM.MODEL.Atendentes", b =>
                {
                    b.Property<int>("AtendenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AtendenteId"));

                    b.Property<int?>("Cargo")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("NomeAtendente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AtendenteId");

                    b.ToTable("Atendentes");
                });

            modelBuilder.Entity("BlazorApp1.MVVM.MODEL.Atendimentos", b =>
                {
                    b.Property<int>("AtendimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AtendimentoId"));

                    b.Property<int>("AtendenteId")
                        .HasColumnType("int");

                    b.Property<int>("ClientesClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data_Atendimento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Data_Inclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Problema")
                        .HasColumnType("longtext");

                    b.HasKey("AtendimentoId");

                    b.HasIndex("AtendenteId");

                    b.HasIndex("ClientesClienteId");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("BlazorApp1.MVVM.MODEL.Clientes", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ClienteId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BlazorApp1.MVVM.MODEL.Empresas", b =>
                {
                    b.Property<int>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmpresaId"));

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("EmpresaId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("BlazorApp1.MVVM.MODEL.Atendimentos", b =>
                {
                    b.HasOne("BlazorApp1.MVVM.MODEL.Atendentes", "Atendentes")
                        .WithMany("Atendimentos")
                        .HasForeignKey("AtendenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.MVVM.MODEL.Clientes", "Clientes")
                        .WithMany()
                        .HasForeignKey("ClientesClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendentes");

                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("BlazorApp1.MVVM.MODEL.Clientes", b =>
                {
                    b.HasOne("BlazorApp1.MVVM.MODEL.Empresas", "Empresa")
                        .WithMany("Clientes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("BlazorApp1.MVVM.MODEL.Atendentes", b =>
                {
                    b.Navigation("Atendimentos");
                });

            modelBuilder.Entity("BlazorApp1.MVVM.MODEL.Empresas", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
